export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

//Get Products types....
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const FILTER_PRODUCTS_BY_CATEGORY_REQUEST = 'FILTER_PRODUCTS_BY_CATEGORY_REQUEST';
export const FILTER_PRODUCTS_BY_CATEGORY_SUCCESS = 'FILTER_PRODUCTS_BY_CATEGORY_SUCCESS';
export const FILTER_PRODUCTS_BY_CATEGORY_FAILURE = 'FILTER_PRODUCTS_BY_CATEGORY_FAILURE';
export const  GET_PRODUCTS_RESET = 'GET_PRODUCTS_RESET'

//Get Categories types....
export const GET_CATEGORIES_LIST_REQUEST = "GET_CATEGORIES_LIST_REQUEST"; 
export const GET_CATEGORIES_LIST_SUCCESS = "GET_CATEGORIES_LIST_SUCCESS"; 
export const GET_CATEGORIES_LIST_RESET = "GET_CATEGORIES_LIST_RESET"; 
export const GET_CATEGORIES_LIST_FAILURE = "GET_CATEGORIES_LIST_FAILURE"; 

//Update product
export const UPDATE_SEARCH = "UPDATE_SEARCH"; 
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"; 
export const RESET_SEARCH = "RESET_SEARCH"; 
export const RESET_CATEGORY = "RESET_CATEGORY"; 